allow_half_size_if_neutral: true
bars_timeframe_minutes: 1
corr_min: 0.55
corr_tight_threshold: 0.85
corr_weak_threshold: 0.65
efficiency_weight: 0.25
flow_weight: 0.35
gamma_expansion_threshold: 0.01
gamma_near_wall_threshold: 0.003
leader_strength_min: 0.4
log_rotation_size_mb: 100
max_history_size: 1000
max_latency_ms: 50
momentum_weight: 0.4
performance_update_interval_hours: 24
persistence_bars: 4
risk_multiplier_high_vol: 0.8
risk_multiplier_tight_corr: 0.8
risk_multiplier_weak_corr: 0.9
session_open_end: 17.0
session_open_start: 15.5
session_power_end: 22.0
session_power_start: 20.0
vol_high_threshold: 0.015
vol_low_threshold: 0.008
window_15m: 7
window_1m: 3
window_5m: 5
