# Configuration des seuils de qualité MIA
# Version: 1.0
# Date: 2025-01-05

# ========== SEUILS PRIX & NORMALISATION ==========
price:
  max_value: 100000.0          # Seuil de division par 100
  tick_alignment_tolerance: 1e-9  # Tolérance alignement tick
  min_value: 0.0               # Prix minimum autorisé
  
# ========== SEUILS VOLUMES ==========
volume:
  min_value: 0                 # Volume minimum
  max_value: 10000000          # Volume maximum réaliste
  
# ========== SEUILS QUOTES & SPREAD ==========
quotes:
  max_spread_ticks: 4          # Spread maximum en ticks
  spread_alert_window_seconds: 2.0  # Fenêtre d'alerte spread
  bid_ask_tolerance_ticks: 1   # Tolérance bid/ask vs DOM
  
# ========== SEUILS NBCV ==========
nbcv:
  total_tolerance_percent: 5.0    # Tolérance total ≈ ask+bid
  delta_tolerance_percent: 5.0    # Tolérance delta ≈ ask-bid
  
# ========== SEUILS VIX ==========
vix:
  min_value: 5.0
  max_value: 100.0
  
# ========== SEUILS VOLUME PROFILE ==========
volume_profile:
  max_corrections_percent: 2.0    # % max de VP corrigés
  vah_val_tolerance: 0.0          # VAH doit être ≥ VAL
  
# ========== SEUILS BASEDATA vs TRADES ==========
basedata_trades:
  volume_tolerance_percent: 10.0  # Tolérance volume bar vs trades
  close_tolerance_ticks: 1        # Tolérance close vs dernier trade
  
# ========== SEUILS SÉQUENCE & TEMPS ==========
sequence:
  max_gap: 1000                   # Gap séquence maximum
  gap_alert_window_seconds: 1.0   # Fenêtre d'alerte gap
  
timestamps:
  monotonicity_tolerance_seconds: 0.001  # Tolérance monotonicité
  
# ========== SEUILS QUALITÉ GLOBALE ==========
quality_thresholds:
  quarantine_rate_max: 0.1        # % max en quarantaine
  tick_alignment_min: 99.9        # % min alignement tick
  quote_sanity_min: 99.5          # % min sanity quotes
  dom_shape_min: 99.5             # % min shape DOM
  nbcv_consistency_min: 98.0      # % min cohérence NBCV
  vp_corrections_max: 2.0         # % max corrections VP
  seq_gaps_max: 0                 # Gaps séquence critiques max
  time_monotonicity_violations_max: 0  # Violations monotonicité max

# ========== CONFIGURATION MARCHÉS ==========
markets:
  ES:  # E-mini S&P 500
    tick_size: 0.25
    symbol: "ESU25_FUT_CME"
    max_spread_ticks: 4
    volume_profile_enabled: true
    dom_levels: 20
    
  NQ:  # E-mini NASDAQ
    tick_size: 0.25
    symbol: "NQU25_FUT_CME"
    max_spread_ticks: 4
    volume_profile_enabled: true
    dom_levels: 20
    
  VIX:  # VIX
    tick_size: 0.01
    symbol: "VIX"
    max_spread_ticks: 10
    volume_profile_enabled: false
    dom_levels: 10

# ========== CONFIGURATION FICHIERS ==========
files:
  unified_output: "mia_unified_YYYYMMDD.jsonl"
  quarantine_output: "mia_quarantine_YYYYMMDD.jsonl"
  offline_output: "mia_offline_YYYYMMDD.jsonl"
  quality_summary: "mia_quality_summary_YYYYMMDD.json"
  max_file_size_mb: 100
  compression_threshold_mb: 50
